name: alsalman_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  azlistview: ^2.0.0-nullsafety.0
  bloc: ^8.1.0
  cached_network_image: ^3.2.1
  cached_network_svg_image: ^0.0.4
  carousel_slider: ^4.2.1
  connectivity_plus: ^2.3.9
  cupertino_icons: ^1.0.2
  custom_searchable_dropdown: ^2.1.1
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  file_picker: ^5.2.6
  firebase_core: ^2.9.0
  firebase_crashlytics: ^3.0.11
  firebase_dynamic_links: ^5.1.0
  firebase_messaging: ^14.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_cache_manager: ^3.3.1
  flutter_datetime_picker: ^1.5.1
  flutter_html: ^3.0.0-alpha.6
  flutter_gif: ^0.0.4
  flutter_inappwebview: ^5.7.2+3
  flutter_local_notifications: ^13.0.0
  flutter_native_splash: ^2.2.9
  flutter_secure_storage: ^7.0.1
  flutter_svg: ^2.0.1
  flutter_tap_payment: ^0.0.4
  font_awesome_flutter: ^10.1.0
  gif: ^2.2.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.4
  http: ^0.13.5
  intl_phone_number_input:
  lazy_load_scrollview: ^1.3.0
  lottie: ^2.3.2
  myfatoorah_flutter: ^2.1.20
  package_info_plus: ^3.0.2
  path_provider: ^2.0.14
  pin_code_fields: ^7.4.0
  requests_inspector: ^2.3.5
  rxdart: ^0.27.7
  share_plus: ^6.3.1
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sign_in_with_apple: ^5.0.0
  size_helper: ^1.1.1+4
  smooth_page_indicator: ^1.0.1
  sticky_headers: ^0.3.0+2
  upgrader:
    git:
      url: "https://github.com/Ahclever2006/upgrader-6.5.0.git"
  url_launcher: ^6.1.5
  video_player: ^2.5.1
  flutter_zoom_drawer: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.11.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - lib/res/translations/
    - lib/res/assets/
    - lib/res/assets/animations/

  fonts:
    - family: Almarai
      fonts:
        - asset: lib/res/fonts/Almarai-ExtraBold.ttf
        - asset: lib/res/fonts/Almarai-Bold.ttf
        - asset: lib/res/fonts/Almarai-Light.ttf
        - asset: lib/res/fonts/Almarai-Regular.ttf
    - family: ComicSans
      fonts:
        - asset: lib/res/fonts/ComicSans-Regular.ttf
        - asset: lib/res/fonts/ComicSans-Medium.ttf
        - asset: lib/res/fonts/ComicSans-Bold.ttf
    - family: Cairo
      fonts:
        - asset: lib/res/fonts/Cairo-Light.ttf
        - asset: lib/res/fonts/Cairo-Regular.ttf
        - asset: lib/res/fonts/Cairo-Medium.ttf
        - asset: lib/res/fonts/Cairo-Bold.ttf
    - family: Roboto
      fonts:
        - asset: lib/res/fonts/Roboto-Light.ttf
        - asset: lib/res/fonts/Roboto-Regular.ttf
        - asset: lib/res/fonts/Roboto-Medium.ttf
        - asset: lib/res/fonts/Roboto-Bold.ttf   
    - family: TimesNewRoman
      fonts:
        - asset: lib/res/fonts/TimesNewRoman-Regular.ttf
        - asset: lib/res/fonts/TimesNewRoman-Bold.ttf     
    - family: CenturyGothic
      fonts:
        - asset: lib/res/fonts/CenturyGothic-Regular.ttf
        - asset: lib/res/fonts/CenturyGothic-Bold.ttf     
    - family: Lato
      fonts:
        - asset: lib/res/fonts/Lato-Regular.ttf
        - asset: lib/res/fonts/Lato-Bold.ttf  

flutter_native_splash:
  color: "#FFFFFF"
  image: lib/res/assets/background.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
